name: GitHub Actions Demo (test unitaires)
on: [push]
jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - uses: actions/checkout@v3 #permet de récupérer les fichiers dans git
      - run: ls -la
      - run: pip3 install pytest
      - run: pytest test_lib.py
      - name: Upload log file
        #if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: my-log-file
          path: logs.txt